# run with --cap-add sys_admin --security-opt label=disable

FROM ghcr.io/ublue-os/bazzite:latest

# TODO: keeping /src in the container sucks
COPY ./src/flatpaks /src/flatpaks

# bwrap tries to write /proc/sys/user/max_user_namespaces which is mounted as ro
# so we need to remount it as rw
RUN mount -o remount,rw /proc/sys && \
    curl --retry 3 -Lo /etc/flatpak/remotes.d/flathub.flatpakrepo https://dl.flathub.org/repo/flathub.flatpakrepo && \
    cat /src/flatpaks | xargs flatpak install -y --noninteractive

# Run the preinitramfs hook copied from bazzite
COPY ./src/titanoboa_hook_preinitramfs.sh /src/titanoboa_hook_preinitramfs.sh
RUN chmod +x /src/titanoboa_hook_preinitramfs.sh && /src/titanoboa_hook_preinitramfs.sh

# Regenerate the initramfs
RUN dnf install -y dracut-live
RUN set -ex && \
    kernel=$(find /usr/lib/modules -maxdepth 1 -type d -printf '%P\n' | grep .) && \
    DRACUT_NO_XATTR=1 dracut -v --force --zstd --reproducible --no-hostonly \
        --add "dmsquash-live dmsquash-live-autooverlay" \
        "/usr/lib/modules/${kernel}/initramfs.img" "${kernel}"

# Install livesys-scripts and configure them
RUN dnf install -y livesys-scripts
RUN sed -i "s/^livesys_session=.*/livesys_session=kde/" /etc/sysconfig/livesys
RUN systemctl enable livesys.service livesys-late.service

# Run the postrootfs hook copied from bazzite
COPY ./src/titanoboa_hook_postrootfs.sh /src/titanoboa_hook_postrootfs.sh
RUN chmod +x /src/titanoboa_hook_postrootfs.sh && /src/titanoboa_hook_postrootfs.sh

# image-builder expects the EFI directory to be in /boot/efi
RUN mkdir -p /boot/efi && \
    cp -av /usr/lib/efi/*/*/EFI /boot/efi/ && \
    cp /boot/efi/EFI/fedora/grubx64.efi /boot/efi/EFI/fedora/gcdx64.efi

# needed for image-builder's buildroot
RUN dnf install -y xorriso isomd5sum

# TODO: We should strive to have just one dnf install and clean all to save time and disk space
